name: jornal

volumes:
  mysql-intro_o_meu_volume:

services:
  app:
    build: .
    ports:
      - 9000:8000
    env_file: "/.env"
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          initial_sync: true
          ignore:
            - virtualenv

        - action: rebuild
          path: requirements.txt
  database:
    image: mysql:latest
    env_file: .env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - mysql-intro_o_meu_volume:/var/lib/mysql